version: "2.4.1"
services:
  app:
    container_name: app_arch
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo

  redis:
    image: redis:latest
    container_name: redis_arch
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

  mongo:
    image: mongo:5.0.3
    container_name: mongo_arch
    ports:
      - "27017:27017"

